### ISSUE TITLE
Missing Upgrades leaderboard button icon

### ISSUE THREAD

**Issue by Alzarath** [ElectricPrism/Risk_Action_Edition_II#3]
The button to access the upgrades leaderboard works, but it is missing an icon.

**Comment by ElectricPrism** [comment]
IIRC basic dialogs can only have text.

There are various dialog systems available to use out there but I honestly feel that complicate the code too much to justify the benefits.

I will have to look into it, I was hoping to do a full UI overhaul at some point however UX Debugging is probably impossible on Linux as I think the hotkeys conflict with all Shells being something like Ctrl + Alt + F7 / F10 or similar.

I will be releasing the SC2Map file, if anyone wants to do a clean version I will merge their Button Icon updates into the main map and push it online.
